version: 2

build:
  os: ubuntu-24.04
  tools:
    python: '3.14'

  jobs:
    pre_build:
      - python -m pip install --requirement docs/requirements.txt
      - zensical build --clean
    post_build:
      - mkdir -p "${READTHEDOCS_OUTPUT}/html"
      - cp --recursive site/* "${READTHEDOCS_OUTPUT}/html"
