PYTHON := 'python -X dev'

_default:
    @just --list

[doc("Build documentation using zensical")]
build:
    {{ PYTHON }} -m zensical build --config-file ../zensical.toml --clean --strict

[doc("Serve the documentation using zensical")]
serve:
    {{ PYTHON }} -m zensical serve --config-file ../zensical.toml --open --strict
